### ISSUE TITLE
Add plugin to Kopano project overview

### ISSUE THREAD

**Issue by fbartels** [bytemine/autodelete#1]
Hi Bytemine,

just rediscovered your plugin. I was wondering if you would be interested in adding your plugin (this and maybe others) to https://github.com/Kopano-dev/projects-and-resources, so it can be easier found by other interested parties.

Regards

**Comment by dra** [comment]
Just created a pull request on z-hub.io to get listed.

**Comment by fbartels** [comment]
Hi @dra,

thanks. I have merged it with https://github.com/Kopano-dev/projects-and-resources/commit/0e482f15a9e20e75a4dd810b8e9d084a52219f5b.

PS: you could also have opened the pull request here on github, but I appreciate the extra effort to do it on stash.z-hub.io!

**Comment by dra** [comment]
@fbartels

> PS: you could also have opened the pull request here on github, but I appreciate the extra effort to do it on stash.z-hub.io!

Your CONTRIBUTING guide said so, so I did :)
